name: tz

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the job every day at midnight UTC
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install moment-timezone

      - name: Generate tz data
        run: node tz.js

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add timezones.json
          git commit -m "Update timezone data" || echo "No changes to commit"
          git push
